import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen h-fit bg-blue-100 overflow-y-scroll overflow-x-hidden flex flex-col">
        <div className="w-full h-20  text-3xl text-white">header</div>
        <div className="w-full min-h-max h-fit bg-gray-100 flex justify-center ">
          <div className="bg-white w-4/5 border border-gray-200 flex">
          {children}
            </div>
            </div>
        <div className=" h-28">footer</div>
        {/* add footer */}
      </body>
    </html>
  );
}
